### PR TITLE
Add upload-service

### PR DESCRIPTION
**Pull request by zpchavez**
https://synapse.leankit.com/Boards/View/285322106/334785439

### CODE REVIEW

**Comment by spruce-bruce** [comment]
Looks ok to me.

Would this make sense as a hapi plugin in its own repo instead of a service in the template? Is this something we expect to have to change for every project?

**Comment by zpchavez** [comment]
Hmm. Guess it could be a hapi plugin. I don't know if I like hapi plugins for providing methods. Seems better for plugging into stuff. This could be it's own repo though. On the plus side people might actually use it then. On the negative side people might actually use it then.

**Comment by spruce-bruce** [comment]
I'm OK with hapi plugins for methods, but I get it. I don't know how to make this its own repo and integrate it using electrolyte?

The main benefit of this being its own thing is that we can easily get updates to this in our projects when updates happen. Like if the resumable.js api changes and we have to update this code it'll be harder to match versions of this with resumable.js versions.

**Comment by zpchavez** [comment]
Yeah. Should be it's own thing.

**Pull request closed without merging**
